export const translationsEn = {
    brand: "Mind School",
    course: "Course",
    bookAnAppoinment: "Book an apointment",
    live: "live",
    group: "Group",
    store: "Store",
    login: "Login",
    signUp: "Sign up",
    myAccount: "My account",
    logout: "Logout",
    profile: "Profile",
    myCourses: "My Courses",
    paymentHistory: "Payment History",
    myFeedbacks: "My Feedbacks",
    deactivateAccount: "Deactivate Account",
    or: "Or",
    login_with_email:"Login with Email",
    login_with_gmail:"Login with Gmail",
    login_with_facebook:"Login with Facebook",
    forgot_password:"Forgot password?",
    no_account:"Don't have an account? Sign Up",
    email:"Email",
    password:"Password",
    quiet_the_mind:"Quiet the mind and the soul will speak",
    when_meditation_mastered:"When meditation is mastered, the mind is unwavering like the flame of a candle in a windless place",
    sign_up_now:"Sign Up Now",
    our_courses:"Our Courses",
    see_all:"See All",
    buy:"Buy",
    course_details:"Course Details",
    instructor_details:"Instructor Details",
    meet_our_instructors:"Meet Our Instructors",
    our_achievements:"Our Achievements",
    teachers:"Teachers",
    videos:"Videos",
    users:"Users",
    subscribers:"Subcribers",
    why_love_mindschool:"Why people love Mind School",
    download_app:"Download our Mobile App",
    to_take_care_of_your_health:"to take care of your mental health",
    selected:"Selected",
    about:"About"

  };
  
export const translationsBn = {
    brand: "মাইন্ড স্কুল",
    course: "কোর্স",
    bookAnAppoinment: "সাক্ষাৎকার",
    live: "লাইভ",
    group: "গ্রুপ",
    store: "স্টোর",
    login: "লগইন",
    signUp: "সাইন আপ",
    myAccount: "একাউন্ট",
    logout: "লগআউট",
    profile: "প্রোফাইল",
    myCourses: "আমার কোর্স",
    paymentHistory: "পেমেন্ট ইতিহাস",
    myFeedbacks: "আমার ফিডবেক",
    deactivateAccount: "ডিএকটিভ একাউন্ট",
    or:"অথবা",
    login_with_email:"ইমেইল দিয়ে লগইন করুন",
    login_with_gmail:"জিমেইল দিয়ে লগইন করুন",
    login_with_facebook:"ফেসবুক দিয়ে লগইন করুন",
    forgot_password:"পাসওয়ার্ড ভুলে গেছেন?",
    no_account:"অ্যাকাউন্ট নেই? নিবন্ধন করুন",
    email:"ইমেইল",
    password:"পাসওয়ার্ড",
    quiet_the_mind:"মন শান্ত করুন এবং দেখুন আত্মা কথা বলবে",
    when_meditation_mastered:"যখন ধ্যান আয়ত্ত করা হয়, তখন মন বাতাসহীন জায়গায় মোমবাতির শিখার মতো অটল থাকে",
    sign_up_now:"এখনই সাইন আপ করুন",
    our_courses:"আমাদের কোর্সগুলি",
    see_all:"সবগুলো দেখুন",
    buy:"কিনুন",
    course_details:"কোর্স ডিটেলস",
    instructor_details:"ইন্সট্রাক্টর ডিটেলস",
    meet_our_instructors:"সমস্ত প্রশিক্ষকের সাথে পরিচিত হন",
    our_achievements:"আমাদের অর্জন",
    teachers:"শিক্ষকরা",
    videos:"ভিডিওসমূহ",
    users:"ব্যবহারকারী",
    subscribers:"সাবস্ক্রিবার্স",
    why_love_mindschool:"মানুষ কেন মাইন্ড স্কুল ভালোবাসে",
    download_app:"আমাদের মোবাইল অ্যাপ ডাউনলোড করুন",
    to_take_care_of_your_health:"আপনার মানসিক স্বাস্থ্যের যত্ন নিতে",
    selected:"নির্বাচিত",
    about:"আমাদের তথ্য"


  };